---
title: "Clean up igotu data"
author: "Kaitlyn"
date: "8/24/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(here)
library(dplyr)
library(rgdal)
library(raster)
library(tidyr)
library(adehabitatLT)
library(hms)
library(amt)
```


### Import and clean tracks

Bring in tracks
```{r}
wd <- getwd()
filenames <- list.files(path = paste(wd, "/Data/Hunting/igotu_raw/", sep=""), pattern = NULL, all.files = FALSE, full.names = TRUE, recursive = FALSE, ignore.case = FALSE)
read_csv_filename <- function(filename){
    ret <- read.csv(filename)
    ret$Source <- filename
    ret
}
hunter.csvs <- lapply(filenames, FUN=read_csv_filename)
```

Write function for extracting data from CSVs
```{r}
ExtractIgotuData <- function (X){
  ID <- X[,"Track"]
  unit.time <- X[,"Time"]
  unit.date <- X[,"Date"]
  unit.datetime <- paste(unit.date, unit.time, sep="")
  # translates into POSIXct times
  date_time <- as.POSIXct(strptime(unit.datetime, "%m/%d/%y %H:%M:%S"), tz="America/Los_Angeles")
  # rename lat and long
  lat <-X[,"Latitude"]
  lon <-X[,"Longitude"]
  # spit out as a dataframe
  data.frame(ID=ID, date_time=date_time, lat=lat, lon=lon)
}
```

Download and clean data
```{r}
# generate list of extracted igotu data
extracted.list <- lapply(hunter.csvs, FUN=ExtractIgotuData)

# combine into one
igotu_data_all <- do.call("rbind", extracted.list) 

# add the metadata
metadata <- read.csv(here::here("Data/Hunting/igotu_metadata_times_cleaned.csv")) %>% 
  mutate(Start_time = paste0(Start_time, ":00"),
         End_time = paste0(End_time, ":00"))
igotu_data_all <- left_join(igotu_data_all, metadata)

# strip time
igotu_data_all$Time <- format(igotu_data_all$date_time, format = "%H:%M:%S")
```


filter to 6 individuals arbitrarily (3 who were successful, 3 who were not)
```{r}
igotu_data_all %>% filter(Harvest == "Y") %>% select(ID) %>% unique

igotu_data_all <- igotu_data_all %>% 
  filter(ID %in% c("080815_01", "080915_19", "081917_29", "080915_11", "081317_32", "081515_21"))
```


Remove points before start or after end
```{r}
igotu_data_all$Keep <- "NO"
for(i in 1:nrow(igotu_data_all)) {
  if(as_hms(igotu_data_all$Time[i]) > as_hms(igotu_data_all$Start_time[i]) &&
     as_hms(igotu_data_all$Time[i]) < as_hms(igotu_data_all$End_time[i])) {
    igotu_data_all$Keep[i] <- "YES"
  }
}

igotu_data_cropped <- igotu_data_all %>% 
  filter(Keep == "YES")

write.csv(igotu_data_cropped, "Data/igotu_data_cropped.csv", row.names = F)
```


Subsample to 1 minute
```{r}
hunter_tracks <- mk_track(tbl = igotu_data_cropped, 
                              .x = lon, .y = lat,
                              id = ID, 
                              .t = date_time,
                              crs = CRS("+proj=longlat +ellps=WGS84")) 

hunter_resampled <- hunter_tracks %>%
  nest(data = -"id") %>%
  mutate(resampled_data = map(data, function(x)
    x %>% track_resample(rate = minutes(3),
                         tolerance = seconds(0)))) %>%
  select(id, resampled_data) %>%
  unnest(cols = resampled_data) %>%
  rename(
    lon = x_,
    lat = y_,
    date_time = t_,
    ID = id
  )

igotu_data_1min <- left_join(hunter_resampled, igotu_data_cropped) 

write.csv(igotu_data_1min, "Data/igotu_data_1min.csv", row.names=F)
```
