---
title: "Extract covariate values at points"
author: "Kaitlyn"
date: "8/24/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

Bring in raster layers and iGotU tracks and extract covariate values.

```{r}
library(raster)
library(dplyr)
```

#### Bring in points

```{r}
igotu_data <- read.csv("Data/igotu_data_1min.csv")

# convert coordinates to spatial points
igotu_data.sp <- igotu_data %>% 
  dplyr::select(Longitude, Latitude) %>% 
  SpatialPoints(proj4string=CRS("+proj=longlat +ellps=WGS84")) %>% 
  spTransform(CRS = "+proj=utm +north +zone=10 +ellps=WGS84 +units=m")
```


#### Bring in raster stack
```{r raster stack}
# first import all files in a single folder as a list 
rastlist <- list.files(path = here::here('Data', 'Spatial data', 'Cleaned rasters'),
                       pattern='.tif$', all.files=TRUE, full.names=FALSE)

# import rasters into raster stack
raster.stack <- raster::stack(paste0("Data/Spatial data/Cleaned rasters/", rastlist))
```

#### Extract covariates from raster stack

Also, convert vegetation to a factor and standardize covariates
```{r raster extract}
igotu.raster <- as.data.frame(raster::extract(raster.stack, igotu_data.sp)) 
```

Combine raster metadata with the other data 

Note that I use cbind here, so it's important that the rows be in the same order (they should be...)
```{r combine metadata}
igotu_data_covariates <- cbind(igotu_data, igotu.raster) 
```

Export
```{r}
write.csv(igotu_data_covariates, "Data/igotu_data_1min_covariates.csv", row.names = F)
```

