---
title: "State Space Models (HMM)"
author: "Kaitlyn"
date: "8/21/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

## Explore Hidden Markov Models for Hopland hunter data

```{r}
library(moveHMM)
library(ggplot2)
library(dplyr)
```


Load all tracks (cropped to huntable area in 02-refine-data.Rmd)
```{r}
igotu_data_huntable <- read.csv("Data/igotu_data_huntable_10min_covariates.csv")

# convert UTM units into kilometers
igotu_data_huntable$lon <- igotu_data_huntable$lon/1000
igotu_data_huntable$lat <- igotu_data_huntable$lat/1000

igotu_data_huntable %>% 
  filter(ID == "081317_36") %>% 
  ggplot(aes(x = lon, y = lat)) +
  geom_point() 
```

Prep data for modeling

```{r}
# subset to just a few IDs just to make this manageable for proof of concept
#igotu_data_huntable <- filter(igotu_data_huntable, ID %in% c("081416_19", "080815_01", "081317_36", "081316_17"))

data <- moveHMM::prepData(igotu_data_huntable, type="UTM", coordNames=c("lon","lat"))

hist(data$step)
hist(data$angle)

plot(data[data$ID == "081416_19",])
```

Prep & run model
```{r}
mu0 <- c(0.1,1) # step mean (two parameters: one for each state)
sigma0 <- c(0.1,1) # step SD
zeromass0 <- c(0.1,0.05) # step zero-mass
stepPar0 <- c(mu0,sigma0,zeromass0)

angleMean0 <- c(pi,0) # angle mean
kappa0 <- c(1,1) # angle concentration
anglePar0 <- c(angleMean0,kappa0)

m <- fitHMM(data=data, 
            nbStates=2, 
            stepPar0=stepPar0, 
            anglePar0=anglePar0,
            formula=~elev+chap_edge)

m

plot(m)

states <- viterbi(m)
states

# proportion of time spent in each state
prop.table(table(states)) 

# plot states for a given individual
plotStates(m, animals="081416_19")

plotStates(m)
```

Now try separating successful vs unsuccessful hunters
```{r}
successful <- igotu_data_huntable %>% 
  filter(Harvest == "Y")
unsuccessful <- igotu_data_huntable %>% 
  filter(Harvest == "N")



data.successful <- moveHMM::prepData(successful, type="UTM", coordNames=c("lon","lat"))
data.unsuccessful <- moveHMM::prepData(unsuccessful, type="UTM", coordNames=c("lon","lat"))

hist(data.successful$step, col= 'red', breaks = 50, freq = F); hist(data.unsuccessful$step, col = 'blue', add=T, breaks = 50, freq = F)

hist(data.successful$angle, col= 'red', breaks = 50, freq = F); hist(data.unsuccessful$angle, col = 'blue', add=T, breaks = 50, freq = F)
```

#### Successful vs unsuccessful hunters model

With no transition probabilities
```{r}
m.successful <- fitHMM(data=data.successful, 
            nbStates=2, 
            stepPar0=stepPar0, 
            anglePar0=anglePar0)

m.successful
plot(m.successful)

m.unsuccessful <- fitHMM(data=data.unsuccessful, 
            nbStates=2, 
            stepPar0=stepPar0, 
            anglePar0=anglePar0)

m.unsuccessful
plot(m.unsuccessful)

```



#### Three state model
```{r}
# initial parameters
mu0 <- c(0.1,0.5,3)
sigma0 <- c(0.05,0.5,1)
zeromass0 <- c(0.05,0.0001,0.0001)
stepPar3 <- c(mu0,sigma0,zeromass0)

angleMean0 <- c(pi,pi,0)
kappa0 <- c(1,1,1)
anglePar3 <- c(angleMean0,kappa0)

m3 <- fitHMM(data=data, nbStates=3, stepPar0=stepPar3, anglePar0=anglePar3)

plot(m3)
  
AIC(m, m3)
```

## BPCA

abandoned this after some brief exploration

```{r}
igotu_data_huntable

library(bcpa)

X <- as.numeric(coords@coords[1:100,1])
Y <- as.numeric(coords@coords[1:100,2])
Time <- 1:100
mytrack <- MakeTrack(X,Y,Time)
plot(mytrack)

test_igotu <- igotu_data_huntable %>% 
  filter(ID == "081416_04")

mytrack <- MakeTrack(test_igotu$lon, test_igotu$lat, 
                     Time = test_igotu$date_time)

plot(mytrack)

igotu.VT <- GetVT(mytrack)
head(igotu.VT)
```

